---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mcp-servers

components:
  - ../../components/sops

resources:
  - ./namespace.yaml
  - ./paperless-mcp/ks.yaml
  - ./nextcloud-mcp/ks.yaml
