---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:17

  superuserSecret:
    name: cloudnative-pg-superuser

  storage:
    size: 20Gi
    storageClass: zfs-nfs

  postgresql:
    parameters:
      max_connections: "200"
      shared_buffers: "256MB"

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 1Gi

  monitoring:
    enablePodMonitor: true
