---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fluent-bit-opensearch
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: fluent-bit-opensearch
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        OPENSEARCH_PASSWORD: "{{ .OPENSEARCH_ADMIN_PASSWORD }}"
  dataFrom:
    - extract:
        key: opensearch
