---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: opensearch-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: opensearch-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Admin password for OpenSearch security plugin
        OPENSEARCH_INITIAL_ADMIN_PASSWORD: "{{ .OPENSEARCH_ADMIN_PASSWORD }}"
  dataFrom:
    - extract:
        key: opensearch
