---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: logging

components:
  - ../../components/sops

resources:
  - ./namespace.yaml
  - ./opensearch-operator/ks.yaml
  - ./opensearch-cluster/ks.yaml
  - ./fluent-bit/ks.yaml
  - ./opensearch-sa/ks.yaml
