#!/usr/bin/env python3
"""Check ghcr.io/tensorchord/vchord-scratch for a newer pg18 release than what's
currently pinned in the shared CNPG cluster's postgresql.extensions.vchord
reference. If found: rebuild the repackaged ghcr.io/cypr0/cnpg-vchord-extension
image via .github/vchord-extension/Dockerfile, push it, bump the pin, and open
a PR. Never auto-merges."""
import json
import os
import re
import subprocess
import sys
import urllib.request

REPO_ROOT = subprocess.run(
    ["git", "rev-parse", "--show-toplevel"], capture_output=True, text=True, check=True
).stdout.strip()
CLUSTER_YAML = os.path.join(
    REPO_ROOT, "kubernetes/apps/database/cloudnative-pg/cluster/cluster.yaml"
)
DOCKERFILE = os.path.join(REPO_ROOT, ".github/vchord-extension/Dockerfile")

SOURCE_REPO = "tensorchord/vchord-scratch"
TARGET_IMAGE = "ghcr.io/cypr0/cnpg-vchord-extension"
PG_MAJOR = "18"
TAG_PATTERN = re.compile(rf"^pg{PG_MAJOR}-v(\d+\.\d+\.\d+)$")
PIN_PATTERN = re.compile(
    rf"reference:\s*{re.escape(TARGET_IMAGE)}:pg{PG_MAJOR}-v(\d+\.\d+\.\d+)"
)


def version_tuple(v):
    return tuple(int(p) for p in v.split("."))


def ghcr_anon_token(repo):
    url = f"https://ghcr.io/token?scope=repository:{repo}:pull"
    with urllib.request.urlopen(url, timeout=30) as resp:
        return json.load(resp)["token"]


def latest_source_version():
    token = ghcr_anon_token(SOURCE_REPO)
    versions = []
    url = f"https://ghcr.io/v2/{SOURCE_REPO}/tags/list?n=1000"
    while url:
        req = urllib.request.Request(url, headers={"Authorization": f"Bearer {token}"})
        with urllib.request.urlopen(req, timeout=30) as resp:
            data = json.load(resp)
            link = resp.headers.get("Link")
        for tag in data.get("tags", []):
            m = TAG_PATTERN.match(tag)
            if m:
                versions.append(m.group(1))
        # RFC5988 Link header pagination, e.g. <...&last=foo>; rel="next"
        url = None
        if link:
            m = re.search(r'<([^>]+)>;\s*rel="next"', link)
            if m:
                url = m.group(1)
                if url.startswith("/"):
                    url = "https://ghcr.io" + url
    if not versions:
        raise RuntimeError(f"No tags matching pg{PG_MAJOR}-vX.Y.Z found for {SOURCE_REPO}")
    return max(versions, key=version_tuple)


def current_pinned_version():
    content = open(CLUSTER_YAML).read()
    m = PIN_PATTERN.search(content)
    if not m:
        raise RuntimeError(f"Could not find current vchord extension pin in {CLUSTER_YAML}")
    return m.group(1)


def sh(*args, **kwargs):
    print("+", " ".join(args))
    subprocess.run(args, check=True, cwd=REPO_ROOT, **kwargs)


def main():
    latest = latest_source_version()
    current = current_pinned_version()
    print(f"Current pin: pg{PG_MAJOR}-v{current}, latest upstream: pg{PG_MAJOR}-v{latest}")

    if version_tuple(latest) <= version_tuple(current):
        print("Up to date, nothing to do.")
        return

    new_tag = f"pg{PG_MAJOR}-v{latest}"
    image_ref = f"{TARGET_IMAGE}:{new_tag}"

    sh(
        "docker",
        "build",
        "--platform",
        "linux/amd64",
        "--build-arg",
        f"PG_MAJOR={PG_MAJOR}",
        "--build-arg",
        f"SOURCE_TAG={new_tag}",
        "-t",
        image_ref,
        "-f",
        DOCKERFILE,
        os.path.dirname(DOCKERFILE),
    )
    sh("docker", "push", image_ref)

    content = open(CLUSTER_YAML).read()
    content = PIN_PATTERN.sub(f"reference: {TARGET_IMAGE}:{new_tag}", content)
    open(CLUSTER_YAML, "w").write(content)

    run_id = os.environ.get("GITHUB_RUN_ID", "local")
    branch = f"vchord-bot/bump-{latest}-{run_id}"
    sh("git", "config", "user.name", "vchord-extension-rebuild-bot")
    sh(
        "git",
        "config",
        "user.email",
        "41898282+github-actions[bot]@users.noreply.github.com",
    )
    sh("git", "checkout", "-b", branch)
    sh("git", "add", "kubernetes/apps/database/cloudnative-pg/cluster/cluster.yaml")
    sh(
        "git",
        "commit",
        "-m",
        f"fix(cloudnative-pg): bump vchord extension image to v{latest}",
    )
    sh("git", "push", "origin", branch)

    pr_body = (
        f"Auto-rebuilt `{TARGET_IMAGE}` from upstream `ghcr.io/{SOURCE_REPO}:{new_tag}` "
        f"(was `pg{PG_MAJOR}-v{current}`) and bumped the pin in the shared CNPG cluster's "
        "`postgresql.extensions.vchord.image.reference`.\n\n"
        "**Note:** `shared_preload_libraries` doesn't change here, so this should apply "
        "without a full rolling restart — but a new extension *version* can still require "
        "`ALTER EXTENSION vchord UPDATE` on each database using it, which CNPG does not "
        "run automatically. Check Immich's own database after this lands "
        "(`ALTER EXTENSION vchord UPDATE;` via a psql session against `immichdb` if search/"
        "indexing behaves oddly post-upgrade).\n\n"
        "🤖 Generated by `.github/workflows/vchord-extension-rebuild.yaml`"
    )
    sh(
        "gh",
        "pr",
        "create",
        "--title",
        f"fix(cloudnative-pg): bump vchord extension image to v{latest}",
        "--body",
        pr_body,
        "--base",
        "main",
        "--head",
        branch,
    )


if __name__ == "__main__":
    main()
