apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:mQybJZhTNosuiHTw2MUGGKkKiErV/5UUoITZpQQ5Bv/I7/adZWJOcColBH3nQNRHgWvYaJs=,iv:yRwagANmQU7GqRGNTUaH2lkI9C5Za2y8KG77zdl1Yto=,tag:lDzyXPkgLWMV4pq4txG4rQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpOFliWXNTTkZSQ1BwUkkz
        TWtFakpuUFRjcU16c0tuSmlnL0kvenpGMmprCnJlc2ZmLzZGL1Ywa1p6akV5WTha
        NUV4RnhhWE9mYjh1TkhVSFlZWXhSbzQKLS0tIHI2a3lxVkRSaUJKRmhtU1VLUDQ4
        VVJBejBIOG8yTmRYdG1ZK2M0ZlBNL1EKHN9vhK376LqJWdJpg3eu3WqFSuitOHe8
        Tm9iXe0Fjl5FIwThkYPy6P9kkyP8VRxwTPIL4uAxxu/tTgOUrF4u7w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1y9et2axsvlxp6p3aq82ju02c9gmx72dt2nd69ag5fyh3h2y9ydfq3cnxpz
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-31T18:59:30Z"
  mac: ENC[AES256_GCM,data:16tc4VcQjdK3CZwxol57eSxo3yLLAekjjD/VzIKk3hR9bdJDsI5s28iRe7cUNmgrrFXk8LMVKxFfAB7aCoKV66nJAAr8rJXDx1VtdX4ykQ9kD2lP6ogafKxAf1jMcLOZwLW1WGdWcRqiGlo3HUPPuWyYGtWrTmEvJ9JTF1hFwII=,iv:TMKE2lebKjg2A7smRvaX3/4b0ky/IehT4m5md3k9EsA=,tag:WeGVUvbid1j48gsqBvv9sg==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
