apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:uMaJfCjkSRQJedPqCE+w76/1jDUlU7XXs70yiW81LBWLg9/OeOcBSjHEORnLEsvCNeHgKcw=,iv:OqNe26lWhh9A/JLSvVAczc06jEosNkzifkgGFlzPExY=,tag:L0nNjwCFgRSiXCitOHf4BA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3TVlMbzNSM3hIV1RSOXNB
        RDdEbTlHNWpwZ3Z6TXdnWTlSQVlmZUo1a2lRCklCeit2S0R2MG5ySkw2Q3lTRThJ
        WU1ycHZiUDVUWFpQdXJyZTlkQ1hpWUEKLS0tIDhLRzVVM1g4d3VBalA5TG9kODM2
        Q2FKbG95YVJJYnN0WVJtTTZNWE1RcGcKAf93Jj3QX4AlXS/XPNdv9/Hu185DR6cH
        uhQhCHqezLfP7fQ0cus7uPAcEw3o5YS1Uxg+dt1XrGad7C1TGK1fOg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1y9et2axsvlxp6p3aq82ju02c9gmx72dt2nd69ag5fyh3h2y9ydfq3cnxpz
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-31T19:14:10Z"
  mac: ENC[AES256_GCM,data:DlsWTg+u4ycYUfZAiXKWqJEFr5MZAu6XY3/KYmnDMncwDgdx6HGINm/77pPVXkdAs3jMf96auKmt/qrwYzIeNvdsUF0oz0vjdznM3y+/RKv90AxZzC14P97Bm1tyrhDd894JSF3Rri82nHlVyHDTnx6DkfbpBKgXzzFCzb/sig8=,iv:kzothFTSAIPs801xUg28aKEnM4akjZP7r6+dsb+D2xk=,tag:Hu12iDfy/nSxuYPDv4hNwA==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
