apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:N6FXp/SOrZ/Ovg==,iv:ILcfxC/ebWnWJHVHlFd8Z1FUlJQrG9636YkbYmLGzvw=,tag:ardukpU/bP5Pri1h+T2lQw==,type:str]
    SECRET_NFS_SERVER: ENC[AES256_GCM,data:OvbpaKbK1hPsqWLL,iv:Kq5ZFzjn/o5gegRzSbznQTQJmIlAzThbVNN4ShaKdDc=,tag:tGZIMyPJM52XkH2/Hf0Zmg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTVVplb0ZMODR2VHc3N2o0
            M09yZFZZK1RubGVEL0U5Ujc5SHFrMUMvNjN3Ckd1L0Q1YjBSSFBtOXJ5NTlIOEp3
            dVFLQ3Yvd0poUEtRM2h5UHFLYW9yNTgKLS0tIDRPVXpTb3Zqd2NaNmdaUTVYdElO
            U002WDY5TENaYjlFRG5hc3BMSUlvWjgKCrbqo8aJC+cc2OzDSsh2YuwjF594V6c2
            7/EZ94fQbCen5+tjl3cAx7F9uKfsir1eHYcZSk6A6q+fpdcyAEASqQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1y9et2axsvlxp6p3aq82ju02c9gmx72dt2nd69ag5fyh3h2y9ydfq3cnxpz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-01T12:18:59Z"
    mac: ENC[AES256_GCM,data:4xaIs6XyCyQUZi9v2DfLm2JCL99nhw6gkjgiBXwXA32k0yiG8j/endv19jbBmscPViJ9VI9GiOQm55i9eps+MeLOHmWdqwj6NEHOSXHWXvKxwlrLpQmglHP0KrW4YcPPAcQ8KHiBIVy9j8aYMzPu6MH/HJWyekYsGZa78jW58gA=,iv:w08yrn6JuODNhMlha1gQVe8WF+77ZR0wx18zySySfDQ=,tag:8szTHPe8+r0JeiguSc4X7g==,type:str]
    mac_only_encrypted: true
    version: 3.13.1
