apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:N6FXp/SOrZ/Ovg==,iv:ILcfxC/ebWnWJHVHlFd8Z1FUlJQrG9636YkbYmLGzvw=,tag:ardukpU/bP5Pri1h+T2lQw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTVVplb0ZMODR2VHc3N2o0
        M09yZFZZK1RubGVEL0U5Ujc5SHFrMUMvNjN3Ckd1L0Q1YjBSSFBtOXJ5NTlIOEp3
        dVFLQ3Yvd0poUEtRM2h5UHFLYW9yNTgKLS0tIDRPVXpTb3Zqd2NaNmdaUTVYdElO
        U002WDY5TENaYjlFRG5hc3BMSUlvWjgKCrbqo8aJC+cc2OzDSsh2YuwjF594V6c2
        7/EZ94fQbCen5+tjl3cAx7F9uKfsir1eHYcZSk6A6q+fpdcyAEASqQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1y9et2axsvlxp6p3aq82ju02c9gmx72dt2nd69ag5fyh3h2y9ydfq3cnxpz
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-31T19:14:09Z"
  mac: ENC[AES256_GCM,data:XTW/qch9aon/hToYG87hbnY/OrIb2obHiM9GEoLTCWnFC4FSAlE1N+wmOY9GAs+G+V7pG2+yTOoLhmS1UnfJlSPkMT59ZHe8lWHPx+BW2od8s8E2UK44/9IBrQFJTYmc5TiiDeasFeblvhRuBzIBxlrg1A6rNHl3TWZGd0U+lIY=,iv:/Y1dPnr4/HH/WL1LEZzooa+IllgvuRs69WyZLHRgDPo=,tag:A4Iu1soUEwSUQl+vJnfqaA==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
