---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:CLtSv8LUTjcvBw==,iv:iu5irm0mgtI8n75sP9BoYsaB8mSoxsxuKpmKY9BI5og=,tag:SSfBnKp4M6t84lV5yZZB/w==,type:str]
  SECRET_NFS_SERVER: ENC[AES256_GCM,data:kWYPQyOH69apJY3g,iv:sX07tHnFzyl5GdHBzAfHC02uxijshClXpmKkRjUDKOM=,tag:ZDpgf0HxoHz4HTrziRIDAA==,type:str]
  SECRET_ALLOWED_IP: ENC[AES256_GCM,data:8XVg6VkxfnKUooid,iv:b1WPGFd6pB3AZYwGOl/Oi5Hbgzi23tJ66TTVNSQhBHA=,tag:2rsBFvWqGQegKtMtfNyg1A==,type:str]
  SECRET_MAIL_SERVER: ENC[AES256_GCM,data:xG6AXaJLNMLck4m4,iv:I9k52F4xd9Sqj4BmGXockP5bKvlILCkofhlTs85zHYs=,tag:XEMftXUdlxHUMdKu36VGxg==,type:str]
  SECRET_PAPERLESS_IMAP_SERVER: ENC[AES256_GCM,data:fsHKUyD+aLdT/+W1n++Rzbiz6j5fTzZjHw==,iv:SFaf9ppWRUc9gt8noMEnSOdIEv8RobXi7EoLBg4xZbM=,tag:XKEo2/oYVJhc+Ipzc8Mt2A==,type:str]
  SECRET_HERMES_WHATSAPP_USER: ENC[AES256_GCM,data:D/U9SdExl2oBXlq6CA==,iv:7EzzvUp+OhmGrcKKlbMm7brimmD64/FjdjRxI4IVfaU=,tag:NaDzzz7MF4YyYyC0E6YhSQ==,type:str]
  SECRET_PORTFOLIO_DOMAIN: ENC[AES256_GCM,data:kRcMsGWcrJlf+0+/dzEPJA==,iv:dK5cjj7wh3+dbPgG9tbVC+hBM9m8HTWGukKx0vamfj4=,tag:BCf1ucnKc5SLwwvujrBHfA==,type:str]
  SECRET_MAIL_PUBLIC_IP: ENC[AES256_GCM,data:wtYUf6nCfFcp+7Q=,iv:GJV4EKCrdWozP9D+ymARjcGzyac7oacFt2itwJ25kuU=,tag:4eOnW43S6oQRU5cOcUlwhg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKcVB5NVpXMVV4dzNFeEk2
        dkU2TlRQRXF4QUZXVlp3ZSt3OHoxTWtGcGlvCk0zZVhGMERmTHd1VDc0WFYvaklU
        YlB5enhBOEY2OWVSMk5IZ2JtQ2ErblEKLS0tIFJoaXNKamNZbXdIbWVBSDNvZWJX
        ZlhiYW80cUdQdTh5elU4bDVYWFEyYlkKcEy/A7Vl4b/7AJJiERlWF8cHRekbT8ny
        mtCAEfecM5KkVr5MWvlX9EMw0wsgOT38SU1C/dtfepJRE99hegNrAg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1y9et2axsvlxp6p3aq82ju02c9gmx72dt2nd69ag5fyh3h2y9ydfq3cnxpz
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-30T11:23:02Z"
  mac: ENC[AES256_GCM,data:SxtA9VCshAgbaW07oPwowXHpDF4LBuDXHpNTybI+qY46lsjmp85DPetnZcDMy5ygHKVEMQK8azGkPNecWlFHC99zOU/e0BPyXNEh1fANJCYkqEZAY4qRiRJY0GpN+RG8LtrpH8N6RGWcXj5jQXrppA1VtbqU0X8q08NySXScj/o=,iv:0zZDW31ljUorzYVRssT0PRxDvEfjPJY+SQcFLzM2Q9c=,tag:HOwYn9UN0sWeFHNSsOCG6g==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
