apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:pBiqOUlFhyjDzP3rxePviDiiI1Fkcmeom6lSyof+W/E=,iv:2Bj59k+d7tbEyTpVnRLhrUeytOQYaOZXf8qL4GerVZ0=,tag:IMQLjHnFZrtaMXxK0/I8Pw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKT25JL0duYzh3dEdBT3Zi
        QkRza055SHdFNkw5T0FnRldHaDVXWmM3Y2tVCnBEeWVVL3diSWNvWldmaEpnS09z
        WGhiUWV1ejFpTEtLRzN2aW1UcFFGYjgKLS0tIFBVUkdKSU1HQ1NPbU0yQ1BjdXly
        VG0yTHVxYnVMbUhnM2d2dEdORC9WbEUK4YaAjxp3F9UA9+SX7EiXuB9IXolScx1I
        PNqi6NJ7iMQrcivywWG+YTTIkYNUyLmMKJEAcjwNprbNZDXynECa8Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1y9et2axsvlxp6p3aq82ju02c9gmx72dt2nd69ag5fyh3h2y9ydfq3cnxpz
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-31T18:59:30Z"
  mac: ENC[AES256_GCM,data:XFRps5lAY3zIHJjl3DwXHiiAmPtYo5p/pJ5+ddug9zOtmIHJGq4HX0XCBOmjEjM4a4xkluZnTu1+fJXW+9eyjrFkDgfrfiTIdHNPaPPCmo8iQW+s8BqnVM4FhQoiQnmobl7/VyBnO8yPFe1yGBCX+TZzX2R4RSOxkCKfV6JtYjM=,iv:3BpFHeM/JkWHKeS8NwvnEhUQkcfKEswpX6Q7DydeRew=,tag:g0KyWTwj+57kSt5Rp7I41g==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
