---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-proxmox-oidc
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: authentik-proxmox-oidc
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        PROXMOX_CLIENT_ID: "{{ .PROXMOX_CLIENT_ID }}"
        PROXMOX_CLIENT_SECRET: "{{ .PROXMOX_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: proxmox
