---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: authentik-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        AUTHENTIK_SECRET_KEY: "{{ .AUTHENTIK_SECRET_KEY }}"
        AUTHENTIK_POSTGRESQL__NAME: "authentik"
        AUTHENTIK_POSTGRESQL__HOST: "postgres-rw.database.svc.cluster.local"
        AUTHENTIK_POSTGRESQL__PORT: "5432"
        AUTHENTIK_POSTGRESQL__USER: "{{ .AUTHENTIK_POSTGRESQL_USER }}"
        AUTHENTIK_POSTGRESQL__PASSWORD: "{{ .AUTHENTIK_POSTGRESQL_PASSWORD }}"
        AUTHENTIK_REDIS__PORT: "6379"
        AUTHENTIK_REDIS__DB: "1"
        AUTHENTIK_REDIS__PASSWORD: "{{ .DRAGONFLY_PASSWORD }}"
        MAXMIND_ACCOUNT_ID: "{{ .ACCOUNT_ID }}"
        MAXMIND_LICENSE_KEY: "{{ .LICENSE_KEY }}"
  dataFrom:
    - extract:
        key: authentik
    - extract:
        key: maxmind
    - extract:
        key: dragonfly
