---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: security
resources:
  - ./configmap.yaml
  - ./externalsecret.yaml
  - ./externalsecret-grafana-oidc.yaml
  - ./externalsecret-opensearch-oidc.yaml
  - ./externalsecret-proxmox-oidc.yaml
  - ./externalsecret-paperless-oidc.yaml
  - ./externalsecret-open-webui-oidc.yaml
  - ./externalsecret-nextcloud-oidc.yaml
  - ./externalsecret-immich-oidc.yaml
  - ./externalsecret-pushover.yaml
  - ./helmrepository.yaml
  - ./helmrelease.yaml
  - ./httproute.yaml
  - ./ciliumnetworkpolicy.yaml

configMapGenerator:
  - name: authentik-blueprints
    files:
      - blueprints/001-cisotop-recovery.yaml
      - blueprints/002-cisotop-mfa-setup.yaml
      - blueprints/003-cisotop-turnstile-reputation.yaml
      - blueprints/004-cisotop-passwordless.yaml
      - blueprints/005-cisotop-authentication.yaml
      - blueprints/006-cisotop-enrollment.yaml
      - blueprints/007-cisotop-pushover-notifications.yaml
      - blueprints/01-grafana-oidc.yaml
      - blueprints/02-opensearch-oidc.yaml
      - blueprints/03-proxmox-oidc.yaml
      - blueprints/04-paperless-oidc.yaml
      - blueprints/05-open-webui-oidc.yaml
      - blueprints/06-nextcloud-oidc.yaml
      - blueprints/07-immich-oidc.yaml
      - blueprints/08-kubernetes-oidc.yaml
    options:
      disableNameSuffixHash: true
