---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-terminal-home-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: zfs-nfs
  resources:
    requests:
      storage: 20Gi
