---
# Credentials for Security Analytics setup job
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: opensearch-sa-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: opensearch-sa-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        OPENSEARCH_PASSWORD: "{{ .OPENSEARCH_ADMIN_PASSWORD }}"
        PUSHOVER_TOKEN: "{{ .ALERTMANAGER_PUSHOVER_API_TOKEN }}"
        PUSHOVER_USER: "{{ .PUSHOVER_USER_KEY }}"
  dataFrom:
    - extract:
        key: opensearch
    - extract:
        key: pushover
