---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./configmap-setup.yaml
  - ./job.yaml
  - ./crd-exporter-rbac.yaml
  - ./configmap-exporter.yaml
  - ./cronjob-exporter.yaml
  - ./configmap-dashboard.yaml
  - ./job-dashboard.yaml
  - ./configmap-proxmox-pipeline.yaml
  - ./job-proxmox-pipeline.yaml
  - ./configmap-proxmox-dashboard.yaml
  - ./job-proxmox-dashboard.yaml
  - ./configmap-opnsense-pipeline.yaml
  - ./configmap-opnsense-dashboards.yaml
  - ./job-opnsense.yaml
  - ./configmap-security-dashboards.yaml
  - ./job-security-dashboards.yaml
  - ./ciliumnetworkpolicy.yaml
