apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:OC2omzOaBKJYxKKGgbPZf3y2AJ9OGkaHIy1xiXWBiiGCuyVq0yOIKfXv7JcBNQFmcmmIen7MUlrFLgQoUYeIRXS00+ajHszLo3pOaFNK5jvSyZ392SfV0KzZWV8JjSSZ8NeulnzjTwHTIXK/TuNMmP+5/6HJQ9ELQIOv5WDIuCmlAvvNX1RlL6uslPqeLFEjviFJM2OUKt1Zp1r5n2NQg8mtGov5MQlAjy9oK4TPdtVf84ed,iv:AdelF9cITpRnKKFz47N8kk55ogPc/ZrMRx0VYxJK3cM=,tag:GLQtP7B7zbbubggsoMoxfA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVOE9XN09hR0hDOFBPUjZO
        Vm9yNHQvUTZ0aEZEVTB2SUIvTTBYVHpaREUwCkhWZityS2dHS2pxcWpaVHZVeDRx
        UmxEdmcxYjBqN1JHd3ZCRGd5dFRLbU0KLS0tIFJWUlZYNklId0RQcUQ1bWZtVVF0
        Z1RxN3B0YzNkOVF3ejhCMHZiamR3eG8KL3sWiCXkJ4taa1EzvceAfDGIVbI8VexB
        f9PXpZxl8UwjzeiIwdHaqEkimz8MhsrgL11tLsMAvpQ4YiLtVcr5VA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1y9et2axsvlxp6p3aq82ju02c9gmx72dt2nd69ag5fyh3h2y9ydfq3cnxpz
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-31T19:14:10Z"
  mac: ENC[AES256_GCM,data:gs9TFOodeO0pxgHXQqxkEd4IfmcQhR4YhYo+hW/aFxKGRIVQZHR0zXTcjizN0pFoFPZtcGUkcY8rDaoUAHMeIKrdV2mhml/MyP2ZlkH/MFLWF9V/yU/7G4S1WaMsjhbmOI2MPcWUrhYpS79q0VElSKHX4QM3DpM0URhYI1ALHo4=,iv:/QPcfR7m17ESvpjAH7UF8PSyqFzsf2G4wub38cbNQ6Q=,tag:GvCgHeFc3r2GX0xtEFZJWw==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
