apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:9hbIbF0xg/I4/c0KA9goza998u+8hED+fQFMsp03pfm7LFA/fkXvN/auHX6UczNydZwQuGDKiY/PVB1cJ+7duUrMq+mQFaVqNy89+7UrhaWnNvsK1nOiPWLZts7FWTugJ51nSKQ+hFqSqm+EgmiWdUMRi5cpIIhJnsnZoAoCY0Ra4METGO3QxBHoyY/AEEEsQKSMwroOlZ4pCx+pWQ8LfWj8cdhWREGZkbUZJBlJdaOiC1gd,iv:q19vQ4Un8wv5hBAgZ17eXebveIvM6W70Xt/PZ1YcCjM=,tag:hdK8gJLVF3fmQkmgLpVP8Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4anBPSXZjOENjZVZ5N3M5
        WWJ0NkpoZ1d0NkVSV0YrQkZMUTNKM3ZMWlhNCktRWE9RbEpMYU56Uk1sd2NkQXVs
        OXgrUCtBNThmWDJoZkw3bmhSRUo5NGsKLS0tIHJYeWVoSUVOZWhVeEdncUppYXFD
        QjJPKzVGaUkwM0tYdzF0NFl1c0RROFkKCs1O2qUpdbfsB406k72yu0VHrnOXjteR
        MSXxf8m648oxFRdKFLaIUWNlFtvwByIzkWsHHzeo6FaOCs+3y1nEIw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1y9et2axsvlxp6p3aq82ju02c9gmx72dt2nd69ag5fyh3h2y9ydfq3cnxpz
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-31T18:59:30Z"
  mac: ENC[AES256_GCM,data:g2XKH98Zwuq5njl4zSsgq3dXvTviZP26XyfB/3iLoVE2biH/xWE1cc7kRG5nQeFFlVi97YpIviKNT+VfOF0FBtDH0dRhKMX4jLsPv5yrn4hY0bCXJYpyTg6FptWZzmGbrW/TR0V4nH66YVuHMSb7MvNYJjl4GgkQvbTJDAontK8=,iv:GmqNQJLdRpSOuT2t5Wgd242pUhEhz80jrpLRoaduJlo=,tag:NSyIB7nq8oWhF8E4C7WKDQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
