---
# Pushover credentials for Falcosidekick alerting
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: falcosidekick-pushover
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: falcosidekick-pushover
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        PUSHOVER_APITOKEN: "{{ .ALERTMANAGER_PUSHOVER_API_TOKEN }}"
        PUSHOVER_USERKEY: "{{ .PUSHOVER_USER_KEY }}"
  dataFrom:
    - extract:
        key: pushover
