apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:vLhl2xGhV7OtQfxAaQSgSSMZAPEJKAKY9E1UDD8JEegfFFnt8K8ezCZLdC7QmNmO6V/NWJo=,iv:bdmR6j8wk0kd1PRUucqYDF/tWnTPflZKRzh85VBBe/0=,tag:iW3oy+4h5XvTTQhsbW8hnw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOcXlENitCVFNiYzhpaWFJ
        MTRVUERNdzJ2ZEpSNmJBa1JTd28yRTQ5T0dzCmhnQVB6SzRnaVU2SklSL0JPUHlJ
        Zlo4TEVnQmw0bW42VitVMGxFQXVvdWcKLS0tIHBnbGUzbTFIaGlUa2t0RWlNdmRh
        clFLaHcwQW9GWnRWZ0dSR2NheVNqSm8KvtISG2oj462ppMZecvPg0SDzZNw89XXU
        V/lNrOU7r9voND+WpgstiNQHL/SnBuqf/yQxZ9SHV83m4Oa7pynVDA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1y9et2axsvlxp6p3aq82ju02c9gmx72dt2nd69ag5fyh3h2y9ydfq3cnxpz
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-31T18:59:30Z"
  mac: ENC[AES256_GCM,data:tLEm0SlI+0V9HTQgj2gHJBkwN5ww0rOXICLsCRFAA8v/a+YfLM4fe1C84H4XXCsfy42v2Z5y4In3kowPrEjIMCY+SJnJcvB1Qgg0QqeJtbdsQwRlJ24Fb9HZoGJvbVFbz8WLA/SrEC7GFf8PVAdpdyPNaAlBUsJlAQTPLFuf/pw=,iv:PBKXodHq79Bcf+iYJnLx5CcsBkG+8LEw8uHpE8LAdPs=,tag:uQCV86xJptVPmiezJ/LkPg==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
