apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:7/NSpHgN6wiPkMmwcyEJBbOztrnPTRXQaJ9Sz5XmXIc+nLMB2w6ks56C4sr5a6SG/AJ4Ha8=,iv:D44ebSyF9R9PRTv3g2kYx9b6eyCD/8kMY4H4hzGxcVY=,tag:TTBPngO5q+qGNFFdVvUP2g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSbUJiN0t3dHR0MlBCMDh2
        SVZoWXZiZDVLTlRveW54UFpmc0NxbmpkbWlvCkxIaC8rWitJaGNIeGhhU3RNaHV0
        SFhodzllNzBQejVoWFBydVhqZUNtWUEKLS0tIEVNNFJaMVk4RXVPaEZTanB3LzJ0
        RDNHbjloK0dxWDY1dTlaaUFOQkh6TFEKO9ZFXUeRWd2Top36fGD8q3udiSg/6fCp
        wCu9VblAu04En0bO4xpRIMPLoViHIc44F/DcgQUTzFV8NvXodPTIGA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1y9et2axsvlxp6p3aq82ju02c9gmx72dt2nd69ag5fyh3h2y9ydfq3cnxpz
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-31T19:14:09Z"
  mac: ENC[AES256_GCM,data:E7KaVGozG8It0aQbXD1wXOenJCehypZgXHI+4FwHIIcgIYJhFt17OY0nqr36GWsTb831uDCzR3Qf817u4OgECEJeWiDwvwHv7qI4XD7f63Pr6CGIm1LxfMKgU8aMoEbuPEm1+SMMSSnbwXpq8H9bPq9sWgOFemnW7fnIC9B7m4U=,iv:CUXplI+Ryev6zR0OwvKh9hOpaocCZV+TNOEVXQTsi38=,tag:6qIooqmaZuKelnjv0TsN8g==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
