---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-pushover
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: alertmanager-pushover
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        alertmanager.yaml: |
          global:
            resolve_timeout: 5m
          inhibit_rules:
            - source_matchers:
                - severity = "critical"
              target_matchers:
                - severity = "warning"
              equal:
                - namespace
                - alertname
          receivers:
            - name: "null"
            - name: pushover
              pushover_configs:
                - user_key: "{{ .PUSHOVER_USER_KEY }}"
                  token: "{{ .ALERTMANAGER_PUSHOVER_API_TOKEN }}"
                  priority: 0
                  retry: 60s
                  expire: 3600s
                  send_resolved: true
          route:
            group_by: ["namespace", "alertname"]
            group_wait: 30s
            group_interval: 5m
            repeat_interval: 12h
            receiver: pushover
            routes:
              - receiver: "null"
                matchers:
                  - alertname = "InfoInhibitor"
              - receiver: "null"
                matchers:
                  - alertname = "Watchdog"
              - receiver: pushover
                matchers:
                  - severity =~ "warning|critical"
  dataFrom:
    - extract:
        key: pushover
