---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: crd-exporter
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crd-exporter-reader
rules:
  # Trivy
  - apiGroups:
      - "aquasecurity.github.io"
    resources:
      - vulnerabilityreports
      - configauditreports
      - exposedsecretreports
    verbs:
      - "get"
      - "list"
  # Velero (backup evaluation dashboard)
  - apiGroups:
      - "velero.io"
    resources:
      - backups
    verbs:
      - "get"
      - "list"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crd-exporter-reader
subjects:
  - kind: ServiceAccount
    name: crd-exporter
    namespace: logging
roleRef:
  kind: ClusterRole
  name: crd-exporter-reader
  apiGroup: rbac.authorization.k8s.io
