---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/postgresql.cnpg.io/database_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: firecrawl
spec:
  name: firecrawl
  owner: firecrawlusr
  encoding: UTF8
  cluster:
    name: postgres
