---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/postgresql.cnpg.io/database_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: open-webui-rag
spec:
  name: openwebuidbrag
  owner: openwebuiusr
  cluster:
    name: postgres
  # pgvector for RAG embeddings (VECTOR_DB=pgvector in open-webui)
  extensions:
    - name: vector
