---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: open-webui-db-role
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: open-webui-db-role
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        username: openwebuiusr
        password: "{{ .OPENWEBUI_DB_PASS }}"
  dataFrom:
    - extract:
        key: openwebui
