---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-db-role
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: paperless-db-role
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: kubernetes.io/basic-auth
      data:
        username: paperlessusr
        password: "{{ .PAPERLESS_DBPASS }}"
  dataFrom:
    - extract:
        key: paperless
