---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud-db-role
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: nextcloud-db-role
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # CNPG managed roles require both username and password keys
        username: nextcloudusr
        password: "{{ .NEXTCLOUD_POSTGRESQL_PASSWORD }}"
  dataFrom:
    - extract:
        key: nextcloud
