---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-db-role
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: authentik-db-role
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        username: authentikusr
        password: "{{ .AUTHENTIK_POSTGRESQL_PASSWORD }}"
  dataFrom:
    - extract:
        key: authentik
