---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mailu-db-role
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: mailu-db-role
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        username: mailuusr
        password: "{{ .MAILU_POSTGRESQL_PASSWORD }}"
  dataFrom:
    - extract:
        key: mailu
