---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: stalwart-db-role
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: stalwart-db-role
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        username: stalwartusr
        password: "{{ .STALWART_POSTGRESQL_PASSWORD }}"
  dataFrom:
    - extract:
        key: stalwart
