---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret-authentik.yaml
  - ./database-authentik.yaml
  - ./externalsecret-paperless.yaml
  - ./database-paperless.yaml
  - ./externalsecret-open-webui.yaml
  - ./database-open-webui-app.yaml
  - ./database-open-webui-rag.yaml
  - ./externalsecret-nextcloud.yaml
  - ./database-nextcloud.yaml
  - ./externalsecret-hermes-agent-trading.yaml
  - ./database-hermes-agent-trading.yaml
  - ./externalsecret-hermes-agent-trading-readonly.yaml
