---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: zfs-nfs
  resources:
    requests:
      storage: 200Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-consume-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: zfs-nfs
  resources:
    requests:
      storage: 5Gi
