---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud-whiteboard-env
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  refreshInterval: "1h"
  target:
    name: nextcloud-whiteboard-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        WHITEBOARD_JWT_SECRET_KEY: "{{ .WHITEBOARD_JWT_SECRET_KEY }}"
        REDIS_URL: "redis://:{{ .DRAGONFLY_PASSWORD }}@dragonfly.database.svc.cluster.local:6379/3"
  dataFrom:
    - extract:
        key: collabora
    - extract:
        key: dragonfly
