---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openclaw
resources:
  - ./ocirepository.yaml
  - ./externalsecret.yaml
  - ./externalsecret-paperless.yaml
  - ./externalsecret-nextcloud.yaml
  - ./helmrelease.yaml
  - ./pvc.yaml
  - ./httproute.yaml
  - ./securitypolicy.yaml
  - ./ciliumnetworkpolicy.yaml
  - ./rbac.yaml
