---
apiVersion: v1
kind: ConfigMap
metadata:
  name: searxng-settings
data:
  settings.yml: |
    use_default_settings: true
    server:
      limiter: false
      image_proxy: false
    search:
      safe_search: 0
      autocomplete: ""
      default_lang: ""
      formats:
        - html
        - json
