---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-webui-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: zfs-nfs
  resources:
    requests:
      storage: 50Gi
