---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./clusterpolicy-pod-security.yaml
  - ./clusterpolicy-seccomp-default.yaml
  - ./clusterpolicy-rbac-cluster-admin.yaml
  - ./clusterpolicy-rbac-least-privilege.yaml
  - ./clusterpolicy-default-serviceaccount.yaml
