---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-ai
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  refreshInterval: "1h"
  target:
    name: paperless-ai-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        PAPERLESS_API_TOKEN: "{{ .PAPERLESS_API_TOKEN }}"
        CUSTOM_API_KEY: "{{ .OPENROUTER_PAPERLESSAI_API_KEY }}"
  dataFrom:
    - extract:
        key: paperless
    - extract:
        key: openrouter
