---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./ocirepository.yaml
  - ./helmrelease.yaml
  - ./servicemonitor.yaml
  - ./ciliumnetworkpolicy.yaml
  - ./externalsecret-opensearch.yaml
  - ./configmap-stats-exporter.yaml
  - ./cronjob-stats-exporter.yaml
  - ./ciliumnetworkpolicy-stats.yaml
