---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mail

components:
  - ../../components/sops

resources:
  - ./namespace.yaml
  - ./stalwart-bootstrap/ks.yaml
  - ./stalwart/ks.yaml
