---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mail
resources:
  - ./helmrepository.yaml
  - ./ocirepository.yaml
  - ./externalsecret.yaml
  - ./certificate.yaml
  - ./dnsendpoint.yaml
  - ./helmrelease-redis.yaml
  - ./ciliumnetworkpolicy-redis.yaml
  - ./helmrelease.yaml
  - ./service-front-webmail-lan.yaml
  - ./ciliumnetworkpolicy.yaml
