---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud-env
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  refreshInterval: "1h"
  target:
    name: nextcloud-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ADMIN_USER: "{{ .NEXTCLOUD_ADMIN_USERNAME }}"
        ADMIN_PASS: "{{ .NEXTCLOUD_ADMIN_PASSWORD }}"
        SMTP_HOST: "{{ .NEXTCLOUD_SMTP_HOST }}"
        SMTP_USERNAME: "{{ .NEXTCLOUD_SMTP_USERNAME }}"
        SMTP_PASSWORD: "{{ .NEXTCLOUD_SMTP_PASSWORD }}"
        DRAGONFLY_PASSWORD: "{{ .DRAGONFLY_PASSWORD }}"
        OIDC_CLIENT_ID: "{{ .NEXTCLOUD_OPENID_CLIENT_ID }}"
        OIDC_CLIENT_SECRET: "{{ .NEXTCLOUD_OPENID_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: nextcloud
    - extract:
        key: dragonfly
---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud-postgres
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  refreshInterval: "1h"
  target:
    name: nextcloud-postgres-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        POSTGRES_DB: "{{ .NEXTCLOUD_POSTGRESQL_DB_NAME }}"
        POSTGRES_HOST: "postgres-rw.database.svc.cluster.local"
        POSTGRES_USER: "{{ .NEXTCLOUD_POSTGRESQL_USERNAME }}"
        POSTGRES_PASSWORD: "{{ .NEXTCLOUD_POSTGRESQL_PASSWORD }}"
  dataFrom:
    - extract:
        key: nextcloud
