---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-pvc
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: zfs-nfs
  resources:
    requests:
      storage: 25Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data-pvc
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: zfs-nfs
  resources:
    requests:
      storage: 200Gi
